[[files]]
name = "stdarch/sde-external-9.48.0-2024-11-25-lin.tar.xz"
sha256 = "3173d2a5369e3385226b488d8b75403951bc14af601435fe707d9f83e0b533e6"
legacy = true

[[files]]
name = "stdarch/sde-external-9.53.0-2025-03-16-lin.tar.xz"
sha256 = "f55138df53378198e8c0a89598351cdb3c5e7f8819e63e472b0bc179afaad34c"
legacy = true

[[files]]
name = "stdarch/sde-external-9.58.0-2025-06-16-lin.tar.xz"
source = "https://downloadmirror.intel.com/859732/sde-external-9.58.0-2025-06-16-lin.tar.xz"
sha256 = "f849acecad4c9b108259c643b2688fd65c35723cd23368abe5dd64b917cc18c0"
license = "https://www.intel.com/content/www/us/en/developer/articles/license/end-user-license-agreement.html"

[[files]]
name = "stdarch/sde-external-10.5.0-2026-01-13-lin.tar.xz"
source = "https://downloadmirror.intel.com/873619/sde-external-10.5.0-2026-01-13-lin.tar.xz"
sha256 = "6542a938efb3fd226c9877d0bdd27b4a18f8330157ce1de6c1f70252f0aa52d5"
license = "https://www.intel.com/content/www/us/en/developer/articles/license/end-user-license-agreement.html"

[[files]]
name = "sde-external-10.8.0-2026-03-15-lin.tar.xz"
source = "https://downloadmirror.intel.com/915934/sde-external-10.8.0-2026-03-15-lin.tar.xz"
sha256 = "50b320cd226acef7a491f5b321fc1be3c3c7984f9e27a456e64894b5b0979dd3"
license = "https://www.intel.com/content/www/us/en/developer/articles/license/end-user-license-agreement.html"

[[files]]
name = "llvm/llvm-22.1.4-x86_64.tar.gz"
sha256 = "23a0f35f08c7ff87307769ef13a211db0ac4c657b43f8c55e51ba6aa6bf566c4"
source = "https://mirrors.edge.kernel.org/pub/tools/llvm/files/llvm-22.1.4-x86_64.tar.gz"
license = "Apache License v2.0 with LLVM Exceptions"
